import 'package:safeboda_clone/models/models.dart';

class SampleData {
  static List<RideModel> sampleRides = [
    RideModel(
      id: "001",
      date: DateTime.now().subtract(const Duration(days: 1)),
      paymentMethod: "SafeBoda Wallet",
      charge: 2975.0,
      pickUp: "Buganda Road, Kampala",
      dropOff: "Nice House of Plastics Kampala",
      duration: const Duration(minutes: 14),
      riderId: "SB-001",
      receiptId: "R-001",
    ),
    RideModel(
      id: "002",
      date: DateTime.now().subtract(const Duration(days: 2)),
      paymentMethod: "Cash",
      charge: 4000.0,
      pickUp: "Bugolobi",
      dropOff: "Ntinda",
      duration: const Duration(minutes: 14),
      riderId: "SB-001",
      receiptId: "R-002",
    ),
    RideModel(
      id: "003",
      date: DateTime.now().subtract(const Duration(days: 1)),
      paymentMethod: "SafeBoda Wallet",
      charge: 2975.0,
      pickUp: "Buganda Road, Kampala",
      dropOff: "Nice House of Plastics Kampala",
      duration: const Duration(minutes: 14),
      riderId: "SB-002",
      receiptId: "R-003",
    ),
    RideModel(
      id: "004",
      date: DateTime.now().subtract(const Duration(days: 2)),
      paymentMethod: "Cash",
      charge: 4000.0,
      pickUp: "Bugolobi",
      dropOff: "Ntinda",
      duration: const Duration(minutes: 14),
      riderId: "SB-002",
      receiptId: "R-004",
    ),
  ];

  static List<RiderModel> sampleRiders = [
    RiderModel(
      id: "SB-001",
      name: "John Doe",
      phone: "0712345678",
      helmentId: "SB-001",
    ),
    RiderModel(
      id: "SB-002",
      name: "Jane Doe",
      phone: "0712345678",
      helmentId: "SB-002",
    ),
  ];

  static List<ReceiptModel> sampleReceipts = [
    ReceiptModel(
      id: "R-001",
      baseFare: 500,
      time: 945,
      distance: 2507,
      peakHourPrice: 1580,
      minPrice: 2000,
      subTotal: 5532,
      rounding: -32,
      discount: -525,
      rideCost: 2975,
      paidSafeBodaCash: 0,
      paidSafeBodaWallet: 2975,
    ),
    ReceiptModel(
      id: "R-002",
      baseFare: 500,
      time: 945,
      distance: 2507,
      peakHourPrice: 1580,
      minPrice: 2000,
      subTotal: 5532,
      rounding: -32,
      discount: -525,
      rideCost: 2975,
      paidSafeBodaCash: 0,
      paidSafeBodaWallet: 2975,
    ),
    ReceiptModel(
      id: "R-003",
      baseFare: 500,
      time: 945,
      distance: 2507,
      peakHourPrice: 1580,
      minPrice: 2000,
      subTotal: 5532,
      rounding: -32,
      discount: -525,
      rideCost: 2975,
      paidSafeBodaCash: 0,
      paidSafeBodaWallet: 2975,
    ),
    ReceiptModel(
      id: "R-004",
      baseFare: 500,
      time: 945,
      distance: 2507,
      peakHourPrice: 1580,
      minPrice: 2000,
      subTotal: 5532,
      rounding: -32,
      discount: -525,
      rideCost: 2975,
      paidSafeBodaCash: 0,
      paidSafeBodaWallet: 2975,
    ),
  ];
  static UserModel myAccount = UserModel(
    id: "0001",
    firstName: "Joe",
    lastName: "Doe",
    phoneNumber: "+256773383412",
  );
}
